version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 4.0.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 3.0.0
  - dependency-name: gatsby-plugin-sass
    versions:
    - 4.0.2
  - dependency-name: gatsby-plugin-offline
    versions:
    - 4.0.0
  - dependency-name: gatsby
    versions:
    - 3.0.0
    - 3.0.1
    - 3.0.2
